name: Python Script Automation - On Merge Main

on:
  pull_request:
    branches: [main]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you require

      - name: Install dependencies
        run: pip install --upgrade pip  # If you have any dependencies, specify them in requirements.txt

      - name: Get sender credential
        run: echo "EMAIL_SENDER_CREDENTIAL_1=${{ secrets.EMAIL_SENDER_CREDENTIAL }}" >> $GITHUB_ENV

      - name: Access GitHub variables
        run: |
          echo "REPICIENTS_LIST: ${{ github.EMAIL_RECIPIENTS }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"

      - name: Send Email
        run: python send_email.py -pw br3very4231
