name: Python Script Automation - On Merge Main

on:
  push:
    branches: [main]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you require

      - name: Install dependencies
        run: pip install numpy==1.25.0 pandas==2.0.3 dropbox==11.36.2  # If you have any dependencies, specify them in requirements.txt

      - name: Get sender credential
        run: echo "ACCESS_TOKEN=${{ secrets.DROPBOX_ACCESS_TOKEN }}" >> $ACCESS_TOKEN

      - name: Run Python script with current date
        run: python dropbox_upload.py -tk $ACCESS_TOKEN